INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Neon Harbor', 'A disillusioned dockworker uncovers a smuggling ring and must choose between quiet survival and loud justice.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Clockwork Orchard', 'In a town where timekeeping is law, a botanist finds a tree that blooms one hour into the future.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Paper Satellites', 'Two rival students launch homemade satellites to prove a theory, then catch a signal that should not exist.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Silent Latitude', 'A stranded polar radio operator hears a voice on a dead frequency and follows it across the ice.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Midnight at Kilometer 12', 'A night bus keeps stopping at the same marker, and the passengers realize the route is looping for a reason.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('The Glass Cartographer', 'A mapmaker who etches cities into glass discovers his newest map is changing on its own.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Sunset Protocol', 'A cybersecurity analyst finds an algorithm predicting blackouts—then learns it was written by someone inside the grid.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Echoes in the Elevator', 'Every floor reveals a different year, and a building maintenance worker tries to fix a lift that is breaking reality.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Ash & Apricot', 'After a wildfire, a chef and a firefighter rebuild a community kitchen that becomes the town’s second chance.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Violet Nomads', 'A band of traveling musicians can erase memories with a song, until one night they erase the wrong one.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('The Last Lantern Maker', 'When the sun dims for unknown reasons, a craftsman’s lanterns become a currency—and a target.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Mosaic of Tomorrow', 'A street artist paints murals that appear the next day in real life, drawing the attention of a secret agency.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Northbound Without Maps', 'A mountaineer follows handwritten directions from a stranger and finds a village that does not appear on any chart.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Beneath the Library Steps', 'A librarian discovers a hidden staircase leading to an archive where books remember the readers.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Red Signal Dawn', 'A ham radio hobbyist intercepts a distress call from a city that has been abandoned for decades.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('The Meridian Thief', 'A skilled pickpocket steals a compass that points to people instead of places, and cannot put it down.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Rooftop Weather', 'A meteorologist and a skateboarder chase a microclimate that only forms above the city’s tallest roofs.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Tides of Copper', 'In a coastal factory town, an engineer learns the ocean is carrying metal messages from a missing ship.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('The Ink Between Us', 'A tattoo artist’s ink reveals hidden truths, forcing clients to face what they have been avoiding.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Garden of Small Miracles', 'A retired teacher cultivates a community garden where every plant heals something different—at a cost.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Seven Minutes to Winter', 'A commuter relives the same seven minutes before a storm, trying to save someone he has never met.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Concrete Fireflies', 'Kids in a gray district build glowing drones to light their nights, accidentally exposing a long-buried scandal.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('The Borrowed Skyline', 'A photographer captures a skyline that vanishes from the world the next morning, and the city demands answers.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Velvet Static', 'A late-night DJ receives anonymous vinyl records that predict callers’ futures—until one record predicts his.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('A Train Called Elsewhere', 'A new platform appears at the station, and a conductor must decide who gets to board and who must stay.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('The Algorithm of Rain', 'A data scientist learns the weather can be computed, then discovers someone is editing the forecast on purpose.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Crescent Under Glass', 'A watchmaker builds a lunar model that starts controlling the tides, drawing a sailor into its orbit.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Hollow City Postcards', 'A travel blogger receives postcards from a city with no roads in or out, each signed with her name.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('The Blue Door Agreement', 'Neighbors agree never to open a mysterious door in their hallway—until it opens from the inside.');
INSERT INTO VIDEOS (NAME, DESCRIPTION) VALUES ('Starlight Maintenance', 'A satellite repair crew finds an extra module that was never launched and must trace who put it there.');
