CREATE SEQUENCE IF NOT EXISTS VIDEOS_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS USERS_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS ROLES_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS AUTH_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS ROLES (
    ID BIGINT DEFAULT NEXT VALUE FOR ROLES_SEQ PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
    ID BIGINT DEFAULT NEXT VALUE FOR AUTH_SEQ PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL UNIQUE,
    GRANT VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT DEFAULT NEXT VALUE FOR USERS_SEQ PRIMARY KEY,
    USERNAME VARCHAR(64) NOT NULL UNIQUE,
    PASSWORD VARCHAR(128),
    ROLE_ID BIGINT NOT NULL,
    FOREIGN KEY (ROLE_ID) references ROLES(ID)
);

CREATE TABLE IF NOT EXISTS VIDEOS (
    ID BIGINT DEFAULT NEXT VALUE FOR VIDEOS_SEQ PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(1024)
);

CREATE TABLE ROLE_AUTHORITY (
    role_id BIGINT NOT NULL,
    authority_id  BIGINT NOT NULL,
    PRIMARY KEY (role_id, authority_id),
    FOREIGN KEY (role_id) REFERENCES ROLES(id),
    FOREIGN KEY (authority_id)  REFERENCES AUTHORITIES(id)
);
