CREATE SEQUENCE IF NOT EXISTS VIDEOS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS VIDEOS (
  ID BIGINT DEFAULT NEXT VALUE FOR VIDEOS_SEQ PRIMARY KEY,
  NAME VARCHAR(128) NOT NULL UNIQUE,
  DESCRIPTION VARCHAR(1024)
);
