---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.127.2
    path: /var/nfs-share/app-cli-pv01
  persistentVolumeReclaimPolicy: Recycle
