---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.122.100
    path: /var/nfs-data/pv01
  persistentVolumeReclaimPolicy: Recycle
