---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc01
spec:
  volumeName: pv01
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
