---
apiVersion: v1
kind: ResourceQuota
metadata:
name: compute-resources
spec:
limits:
  - type: "Container"
    max:
      pods: "6"
      cpu: "8"
      memory: "16Gi"
      ephemeral-storage: "5Gi"
    min:
      cpu: "4"
      memory: "4Gi"
      ephemeral-storage: "2Gi"
      pods: "4"
